### ISSUE TITLE
bundle fails: EISDIR: illegal operation on a directory, open

### ISSUE THREAD

**Issue by grundmanise** [facebook/metro-bundler#12]
*bug*

**What is the current behavior?**

When running:
`react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output ./ --sourcemap-output ./`

I got:
`EISDIR: illegal operation on a directory, open './'`

I've tried with `reset-cache`, tried using different directories, tried `sudo` -- nothing helps.

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**

node v.6.11.0
react-native-cli: 2.0.1
react-native: 0.44.0
npm v.3.10.10
macOS v.10.12

--- 

When running Xcode build/run (Release scheme) everything works great.

**Comment by grundmanise** [comment]
It was my inadvertence.. should have specified file with extension in the `--bundle-output` & `--sourcemap-output`

**Comment by moroine** [comment]
Got the same issue thanks for leaving back a comment :+1:

**Comment by SudoPlz** [comment]
I was also passing a directory to ` --sourcemap-output` instead of an actual file.
This used to work, but it broke recently!
