### ISSUE TITLE
JSTransformer ignores timeout option

### ISSUE THREAD

**Issue by cogwheel** [facebook/metro-bundler#23]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

The transformTimeoutInterval is set from a const, but the error message says it should be settable by an option.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Pass transformTimeoutInterval=1 to the bundler
Bundle a package that takes longer than one second
The timout will not occur after one second

Here's the problem: https://github.com/facebook/metro-bundler/blob/master/packages/metro-bundler/src/JSTransformer/index.js#L110 (along with the error message formatting on line 165)

**What is the expected behavior?**

Specified timeout is respected

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**

the issue is in master branch as linked above.

**Comment by cpojer** [comment]
I think the timeout is more like best-effort and it's not always respected. We are currently rewriting the transformers and will try to make sure to consider making this more solid in the new transformers.
