### ISSUE TITLE
An API to customize environment-specific polyfills

### ISSUE THREAD

**Issue by ide** [facebook/metro-bundler#25]
We'd like to be able to exclude some of the built-in polyfills depending on the platform (and ideally other options as well, such as environment variables). The basic use case is to include different polyfills on Android and iOS. An advanced use cases is to include different polyfills for different versions of iOS.

Since the packager already builds a different dependency graph for each platform, the basic use case probably needs very little refactoring to support. This is a proposal:

### API proposal

The user can optionally give Metro a function that customizes the list of polyfills when building the dependency graph. The function receives the default list of polyfill paths (ex: Object.es6.js) and the current platform, and must return a new list of polyfill paths.

```js
function customizePolyfills(defaultPolyfillPaths: string[], platform: string): string[] {
  // Do whatever you want to customize the list of polyfills. Generally you want to remove
  // or add to the default array. Return defaultPolyfillPaths without touching it to be a no-op.
}
```

### Implementation proposal

The Resolver class at `src/Resolver/index.js` defines an instance method called `_getPolyfillDependencies`. The resolver knows which platform it is building the dependency graph for [in `getDependencies` here](https://github.com/facebook/metro-bundler/blob/master/packages/metro-bundler/src/Resolver/index.js#L116). `_getPolyfillDependencies` would get the default list of polyfills and then pass it into the function proposed above and use the returned array.

This proposal doesn't handle the advanced use case (ex: customizing the polyfill list based on an environment variable) but it seems straightforward for the basic use case. What do you think? Is there a simpler or more general approach to customizing the polyfills or dependency graph?

**Comment by ide** [comment]
Just saw that https://github.com/facebook/react-native/commit/ad0fe15e2e1c13daa89249d9598230daf42a4be3 landed. This makes it easier to customize the polyfills but not based on platform since it's a static array.

Do you think you could turn `config.polyfills` into `config.getPolyfills(platform)` or `config.getPolyfills({platform})` or tell me how to submit a PR that spans repos (Metro and RN)?

**Comment by mjesun** [comment]
@ide Thanks for the feedback! I've commented in the RN PR you opened :)

**Comment by ide** [comment]
I'm going to close this since the RN + Metro changes have landed. Thank you for your help!
