### ISSUE TITLE
Documentation for available options

### ISSUE THREAD

**Issue by brentvatne** [facebook/metro-bundler#26]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

I can't find any documentation for the packager options

**What is the expected behavior?**

It would be cool to be able to have documentation for the packager options

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**

N/A

**Comment by raspasov** [comment]
100+ this. I was looking for ways to increase the available memory to each worker that metro-bundler spawns and short of digging through complected mountains or just hacking it in place, I didn't find any other way. I hacked it in place for now... Not fun: every time you have to wipe your node_modules for various fun reason it has be re-done.

**Comment by cpojer** [comment]
@mjesun is working on this, and we are hoping to streamline the public API for Metro soon :) Closing this issue for now as it's on our roadmap and we are actively working on it, so it's not actionable on its own.

**Comment by raarts** [comment]
So, any progress on this?

**Comment by mjesun** [comment]
You can find some of that stuff here: https://facebook.github.io/metro/. Still a lot to document (especially what has been worked lately), but should serve as a basis.
