### ISSUE TITLE
Switching minifiers to uglify-es

### ISSUE THREAD

**Issue by ide** [facebook/metro-bundler#36]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Metro uses uglify v2 for minification. uglify v3 is now out as well as uglify-es, which has the same function signatures as uglify v3 but can consume ES6+, which becomes relevant as JS VMs get upgraded (e.g. people targeting iOS 10+ may want to use a custom .babelrc).

uglify v3 doesn't have a lot of breaking changes, and I believe they don't affect RN, so this should be mostly a matter of updating how uglify is called from Metro, testing minification speed, and looking at bundle size.

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**
Metro 0.11.x

**Comment by cpojer** [comment]
@davidaurelio actually tried and it broke a bunch of stuff at FB, so we reverted him. I'll let him make a call.

**Comment by davidaurelio** [comment]
I will give this another go. I think they fixed the bug I reported.

**Comment by cpojer** [comment]
This was landed.
