### ISSUE TITLE
Can no longer pass in transformTimeoutInterval as opt

### ISSUE THREAD

**Issue by jlo1** [facebook/metro-bundler#38]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
Unable to pass `transformTimeoutInterval` as opt

**What is the expected behavior?**
Would be great to pass this in via `project.ext.react` in build.gradle

Related issue reported under react-native project: https://github.com/facebook/react-native/issues/15401
Original commit that reverted option: https://github.com/facebook/react-native/commit/242ced150c4d44c68f97e2b0cf9722397d438004

**Comment by cpojer** [comment]
We are currently rewriting the transformer, and will consider to fix this :) Closing for now as this specific issue isn't actionable by external users.
