### ISSUE TITLE
Add ability to log stack traces for bundling errors

### ISSUE THREAD

**Issue by TikiTDO** [facebook/metro-bundler#42]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Currently when there is a bundling error the bundler strips off all stack information before printing an error.

The TerminalReporter `_logBundlingError` function states `We do not want to log the whole stacktrace for bundling error, because these are operational errors, not programming errors, and the stacktrace is not actionable to end users.`

**What is the expected behavior?**

There should be an option to enable the bundler to report the full stack information of any errors it encounters, something like a `--verbose` option would suffice.

There are multiple scenarios where having this information would make a developer's live a lot easier (such as the one I am experiencing trying to debug babel issues). Currently I have to resort to modifying module code, and running the bundler within an inspector just to extract information which should realistically be much easier to get at.

**Comment by cpojer** [comment]
I made this change recently, it may not have made it to react-native yet: https://github.com/facebook/metro-bundler/commit/521e25bded6ac8bfac65e592121b6d16ad3de317

**Comment by TikiTDO** [comment]
Good to know, thanks.
