### ISSUE TITLE
TransformCaching module try to collect cache every time I build bundle

### ISSUE THREAD

**Issue by tsyeyuanfeng** [facebook/metro-bundler#46]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
**TransformCaching** module try to collect cache every time I build bundle. **_collectCacheIfOldSync** method returns when `Date.now() - lastCollected > GARBAGE_COLLECTION_PERIOD`.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**
Shouldn't the judgment be `Date.now() - lastCollected < GARBAGE_COLLECTION_PERIOD`？

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**

**Comment by mjesun** [comment]
That makes sense to me as well, but let's double check with @jeanlauliac :)

**Comment by jeanlauliac** [comment]
No, the current code is correct afaik. We want to collect only after the delay between the last collection and now (`Date.now() - lastCollected`) is **longer** than the period/delay, not shorter. If we collect when it's shorter, then it collects all the time.

I may be wrong somewhere. Did you step-by-step debug and notice that it was collecting all the time?

**Comment by tsyeyuanfeng** [comment]
```
  /**
   * When restarting packager we want to avoid running the collection over
   * again, so we store the last collection time in a file and we check that
   * first.
   */
  _collectCacheIfOldSync() {
    const {_rootPath} = this;
    const cacheCollectionFilePath = path.join(_rootPath, 'last_collected');
    const lastCollected = Number.parseInt(
      tryReadFileSync(cacheCollectionFilePath) || '',
      10,
    );
    if (
      Number.isInteger(lastCollected) &&
      Date.now() - lastCollected > GARBAGE_COLLECTION_PERIOD
    ) {
      return;
    }
    const effectiveCacheDirPath = path.join(_rootPath, CACHE_SUB_DIR);
    mkdirp.sync(effectiveCacheDirPath);
    collectCacheSync(effectiveCacheDirPath);
    fs.writeFileSync(cacheCollectionFilePath, Date.now().toString());
  }
```
Currently this function returns when the delay between the last collection and now `(Date.now() - lastCollected)` is longer than `GARBAGE_COLLECTION_PERIOD`. I think this isn't what you mean. This function will call `collectCacheSync` when the delay between the last collection and now `(Date.now() - lastCollected)` is shorter than `GARBAGE_COLLECTION_PERIOD`.

**Comment by jeanlauliac** [comment]
Yup, you're correct, I didn't realise it's an early-return condition. Would you mind sending a PR? ^_^

**Comment by tsyeyuanfeng** [comment]
I've sent it.
