### ISSUE TITLE
blacklist completely ignored

### ISSUE THREAD

**Issue by samuela** [facebook/metro-bundler#58]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The file blacklist is ignored.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

With react-native v0.48.3 `init` a new project and add a `rn-cli.config.js` file to the root directory:

```javascript
const metroBundler = require('metro-bundler');

module.exports = {
  getBlacklistRE: function() {
    console.log("yes, i am being called but no one seems to listen.");
    // ignore everything!
    return metroBundler.createBlacklist([/.*/]);
  },
};
```
Now, run `react-native run-ios` the packager will open up print the message and still bundle everything!

A cursory look through the source code did not uncover any places where the `blacklistRE` option was ever actually _used_ in the code. I couldn't find any tests for `blacklistRE` either.

**What is the expected behavior?**

For the blacklist to work.

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**

metro-bundler 0.11.0
react-native 0.48.3
yarn 0.17.2
macOS

**Comment by samuela** [comment]
For context, I'm trying to blacklist because of https://github.com/invertase/react-native-firebase/issues/414#issuecomment-329947207.

**Comment by samuela** [comment]
Ok, I think running with `npm start -- --reset-cache` before `react-native run-ios` works, so this appears to be a caching issue.

**Comment by cpojer** [comment]
We are now considering the blacklist in the latest version of Metro.

**Comment by samuela** [comment]
@cpojer You mean considering the blacklist for cache invalidation?
