### ISSUE TITLE
Is the `.mjs` file extension resolved by metro bundler?

### ISSUE THREAD

**Issue by mweststrate** [facebook/metro-bundler#59]
Hi all, quick question as library maintainer, is the `.mjs` file extension supported by metro? In order words, will a package json with a `module` field like this work like with webpack (or is `module` ignored completely, which would be fine as well):

`"module": "lib/mobx.mjs"`

**Comment by mweststrate** [comment]
Had some collegues testing it, using `.mjs` extension caused the bundler to fall back to the `"main"` field containing the UMD bundle or our [test package](https://github.com/mobxjs/mobx-utils/commit/66d40e0327aceed6dd69b8d8368664002db440ca#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

**Comment by mweststrate** [comment]
Update: seems that `module` or `jsnext:main` are not picked up by the bundler in the first place. A `react-native` field is picked up (deducted from source code, I couldn't find docs on that)

**Comment by mweststrate** [comment]
What are future plans on this? I have to admit it is quite unobvious as library author how a library should be published to make it suitable for RN, without falling back to UMD / commonjs

**Comment by mweststrate** [comment]
Closing for now, until .mjs has become a bit more mainstream. Still curious on thoughts around this though

**Comment by rafeca** [comment]
Hey @mweststrate! Thanks for bringing this up.

As you mention, `metro-bundler` does not take into account the `module` field on `package.json`, so it should be safe to use this field in a library to expose `.mjs` files as long as the package still exposes a `.js` file in the `main` field.

For now I think it's better to wait until `.mjs` gets more traction (and Node ships a version with support for it) to implement proper support for modules in metro.

In the meantime, RN users can customize the `sourceExts` config param (the same way you did for the default value in #60) to make `metro` parse these files.

If there is a lot of demand of users wanting to use files with the `mjs` extension, we could merge your PR, but for the time being I'd prefer to wait until the dust around ES6 modules settles.

**Comment by cpojer** [comment]
Please send a pull request to the resolution code in "ResolutionRequest", with tests, and we are happy to merge and support this functionality :)

**Comment by mweststrate** [comment]
Tnx! Closed for now, after diving into webpack a bit further, it is not even supported officially there, so probably it is better to wait until webpack has figured it out :). 

For now just added a `react-native` field to the `package.json` of all the libraries, pointing to an ES5/ES module file with old fashioned `.js` extension. That works well with Metro.
