### ISSUE TITLE
no such file or directory, open '/Users/.../project-name/node_modules/metro-bundler/src/Resolver/polyfills/prelude_dev.js'

### ISSUE THREAD

**Issue by natashache** [facebook/metro-bundler#61]
Getting this error all of a sudden. Tried deleting node modules and reinstalling, clearing cache, upgrading react native, reinstalling metro-bundler. None of it worked. 

The path indeed does not exist. In fact I don't see any `src` folder in node_modules/metro-bundler.

I downloaded the `src` folder from this repo and added it to node-modules/metro-bundler. Now the file is definitely there. But it's still showing the same error...saying there's no such file.
![screenshot 2017-09-18 22 29 41](https://user-images.githubusercontent.com/19754530/30573279-ef59ea3a-9cc0-11e7-8d43-637c51ea8896.png)

Anyone has insights on this? 

Update: cleared cache again after adding `src` folder. It worked one time. And then when I rebuild I'm now getting this same error...

**Comment by cpojer** [comment]
Seems like an issue with the concrete Metro/RN install, and shouldn't repro once upgrading/reinstalling with Yarn.
