### ISSUE TITLE
[Feature] HMR with multiple clients

### ISSUE THREAD

**Issue by brentvatne** [facebook/metro-bundler#8]
**What is the current behavior?**

1. Create a new react-native project either with react-native-cli or create-react-native-app
2. Open app on simulator
3. Open app on device
4. Disable live reloading and enable hot reloading on both of them
5. Make changes
6. Only the most recently connected client will update

**What is the expected behavior?**

Both clients should hot reload

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**

Default react-native configuration for 0.45 (react-native-cli) and 0.44 (create-react-native-app). This is a longstanding issue that as far as I know has been present since the inception of HMR in react-native. Yarn 0.24., macOS 10.12.4

**Comment by linnett** [comment]
+1

**Comment by cpojer** [comment]
The HMR code is still in react-native/local-cli.

**Comment by brentvatne** [comment]
@cpojer - is it moving here? if so, where's the best place for this issue? I imagine it will just be ignored or closed on react-native and then have to be re-opened here if it moves to metro

**Comment by cpojer** [comment]
It may move here but for now the code is in react-native and the change needs to be made there. Sorry about the confusion.
