### ISSUE TITLE
Can not install metro-bundler

### ISSUE THREAD

**Issue by alanlong9278** [facebook/metro-bundler#82]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
`npm install metro-bundler` 
metro-bundler@0.0.0
updated 1 package in 1.39s
**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**
metro-bundler@0.20.0
updated 1 package in 1.39s
**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**
npm 5.5.1

**Comment by cpojer** [comment]
please install a version above 0.0.0.

**Comment by alanlong9278** [comment]
I install with the version number, but can not install success too.
```
 react npm install metro-bundler@0.10.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for metro-bundler@0.10.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan/.npm/_logs/2017-10-30T09_22_05_745Z-debug.log
➜  react npm install metro-bundler@0.9.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for metro-bundler@0.9.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan/.npm/_logs/2017-10-30T09_22_20_270Z-debug.log
➜  react npm install metro-bundler@latest
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN alan No description
npm WARN alan No repository field.
npm WARN alan No license field.

+ metro-bundler@0.0.0
removed 407 packages and updated 1 package in 3.368s
```

**Comment by cpojer** [comment]
I don't know what your "react npm" call is, but `yarn add metro-bundler` works for me.

**Comment by alanlong9278** [comment]
react is document name, I just run ``` npm install  metro-bundler@0.10.0 ``` in the react dir, 
The below is my log when running ``` yarn add metro-bundler```
```
yarn add v0.20.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ metro-bundler@0.0.0
✨  Done in 0.43s.
```

**Comment by alanlong9278** [comment]
It can not find any version except 0.0.0, I don't know why @cpojer

**Comment by alanlong9278** [comment]
I find it, it because my registry is the private source, there is no metro-bundle package in the source server. Thanks for helping
