### ISSUE TITLE
[7c69e83] broke remote debugging on React Native

### ISSUE THREAD

**Issue by andrebraga** [facebook/metro-bundler#84]
https://github.com/facebook/metro-bundler/blob/dbb2d44c42e23a83c1b9f51a577afa003f34e6b0/packages/metro-bundler/src/Server/index.js#L529

The change to the case of `_processDebugRequest` to `_processdebugRequest` seems to cause `debuggerWorker.js` of React Native to be incorrectly processed.

Symptoms include the appearance of ```<!doctype html><div><a href="/debug/bundles">Cached Bundles</a></div>``` in the middle of the downloaded `debuggerWorker.js` in VS Code. 

Cross-referencing the following issues that are a manifestation of this.
https://github.com/Microsoft/vscode-react-native/issues/580
https://github.com/Microsoft/vscode/issues/37734

Causes the following error:
```
SyntaxError: Unexpected token <
vm.js:74
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

The `<` above corresponds to the opening of `<!doctype html>`.

**Comment by andrebraga** [comment]
Looks like the actual fix was a bit different (sorry if there was any misdirection, it was 5 AM already when I started to understand what was going on). I'll leave it up to you to see if this is the intended fix, or if my misunderstanding of the issue has some actual value to it. 😅 

https://github.com/Microsoft/vscode-react-native/issues/580

**Comment by rafeca** [comment]
Closing the issue. BTW we've recently removed the `_processdebugRequest` method from the server

**Comment by toannh0104** [comment]
thank you! (y)
