### ISSUE TITLE
Version of UglifyJS seems unstable

### ISSUE THREAD

**Issue by lukemiles** [facebook/metro-bundler#87]
This commit https://github.com/facebook/metro-bundler/commit/b0c79aa19325abedca5a2aac3ce3fb95c9cf4cec and this commit https://github.com/facebook/metro-bundler/commit/1dec296000da4913de8edec4c1c845452f6fdfef seem to be at odds with each other (they effectively undo one another).

`react-native` builds are still breaking with 3.1.0, but clearly this is an uglifyJS issue. I still can't get a release build out with this version of metro-bundler however.

**Comment by lukemiles** [comment]
Not trying to gripe at all by the way, I really appreciate all the work that goes into this project. It just seems like there perhaps is a lack of coordination here. I'm going to fiddle with using different versions of metro-bundler and uglifyJS to figure out what's best here.

**Comment by rafeca** [comment]
Hey @lukemiles,

The downgrade of uglify has purposely been done after all our internal performance tests at FB have showed us that the upgrade to `3.1.8` caused a noticeable performance degradation (there are more details of the issue [here](https://github.com/mishoo/UglifyJS2/issues/2464)).

The uglify people have reacted really quickly and they have a fix almost ready. Once a new version of uglifyJS that does not impact performance has been released, we'll upgrade our dependency to that version.

Also, two important points:
* The downgrade has only been done in metro master (and it's going to be hopefully a temporary change until the issue gets fixed). If we were to release a version of metro before this gets fixed, we would communicate it appropriately to users.
* We've decided to leave the metro dependency on `uglify-es` to `^3.1.1`. This means that even if you depend on metro master you can still choose to keep using the `3.1.8` version (if you're ok with the perf regression), while we at FB will keep using `3.1.1` internally. To do so, make sure to remove the `uglify-es` entry from your yarn.lock file and next time you run `yarn` the latest version will be installed.

Regarding your last question, unfortunately, if you're experiencing the uglify issues that cause an invalid bundle, you'll have to use 3.1.8 and live with the perf regression for a few days. To do so, as I mentioned, you only need to delete the `uglify-es` entry from your yarn.lock and run `yarn`.

I hope that this explanation helps.

**Comment by lukemiles** [comment]
@rafeca I really appreciate you taking your time to reply thoughtfully here. Thanks so much and have a great day/weekend.
