### ISSUE TITLE
Cannot add new dependencies to project

### ISSUE THREAD

**Issue by jarecsni** [facebook/metro-bundler#90]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I tried to add dependencies to my expo project, they are all present in the node_modules folder, however when the packager start it displays errors:

Warning: 'mobx-state-tree' dependency is not installed.

I decided to upgrade to 22.0.0, but I ran into very similar problems (after following the steps on Expo website):

Warning: Installed version 19.0.1 of 'expo' does not satisfy required version ^22.0.0

Not sure what this is, but it looks as though a given installation would be around which I cannot extend / modify. I know it doesn't make much sense, but this is how it looks. Deleting node_modules, reinstalling with yarn, clearing packager cache did not help.

**What is the expected behavior?**
I should be able to add/upgrade dependencies.

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**

node: 7.2.0
npm: 5.51
Not sure about the metro bundler config, sorry.

**Comment by cpojer** [comment]
I don't think this is related to metro, more likely this is related to expo.

**Comment by jarecsni** [comment]
The warnings seem to be coming from the packager

**Comment by jarecsni** [comment]
Just for completeness, deleting the package-lock.json file helped.
