### ISSUE TITLE
Class name mangling

### ISSUE THREAD

**Issue by jneuendorf** [facebook/metro-bundler#91]
I am not sure whether my concern is a bug or a feature.

**Current behavior**

Currently, class names get mangled by `uglify-es` because class names are essentially function names. Some of my code relies on the names of certain classes. Thus, my react native app would crash when running the release build.

Since I had to debug the release it was really hard to find out what is the issue (no console logs, minified code).

**Expected behavior**

Since ES6 introduced classes it should be ok to do something with a class'es name. But that is currently impossible because class names are most likely single characters...

**Suggestions**

From what I found out `uglify-es` does not support an option for this issue.
But maybe there is a workaround:

- Does babel keep track of what functions were classes or can the AST retrieved by babel? If so, the according names could be passed to uglify's blacklist (reserved names).
  -> _automatic name detection_
- Maybe each JS file could be uglified separately (I don't know if that is already the case). That way files containing classes whose names are important could not be mangled.
  -> _manual name detection_

**metro-bundler configuration & versions**

metro-bundler is used by `react-native` 0.47.2. I don't have any custom configuration.

- metro-bundler: 0.9.2
- node: 8.3.0
- yarn: 1.3.2
- npm: 5.4.2
- OS: macOS Sierra / 10.12.6 (16G29)

**Comment by cpojer** [comment]
In what code do you rely on class names? Can you give us an example of what code exactly breaks for you?

**Comment by jneuendorf** [comment]
Sure. I am using `react-navigation`. A `Navigator` requires a dictionary mapping names to options (see https://reactnavigation.org/docs/navigators/stack).
My screens used for the navigator extend the same class (which is not `React.Component` - I know many people do not agree with this but that's not the point here :wink:).
Here's an example:

```javascript
class SuperScreen extends React.Component {
    // default implementation
    static getScreenName() {
        return this.name.replace("Screen", "")
    }
}
class LoginScreen extends SuperScreen {}
class ProfileScreen extends SuperScreen {}
```

I could create a `Navigator` like so:

```javascript
const myNavigator = StackNavigator({
    Login: {screen: LoginScreen},
    Profile: {screen: ProfileScreen}
})
```

To save some boilerplate code I wrote a helper function:

```javascript
const createNavigator = function(navigatorFactory, screens) {
    // 'dict' does to opposite of Object.entries.
    const screenData = dict(screens.map(screen =>
        [screen.getScreenName(), {screen}]
    ))
    return navigatorFactory(screenData)
}
```

Now, I create `myNavigator` like this:

```javascript
const myNavigator = createNavigator(StackNavigator, [LoginScreen, ProfileScreen])
```

**Comment by cpojer** [comment]
I encourage you not to rely on class names in production code. The way this is generally solved is by encoding the name as a string. One reason why that is superior is that when you add localization, you will be unable to use the class name and you have to duplicate the class name as a string regardless.

I'm gonna close this as wontfix because I don't think we want to support this behavior at this time.

**Comment by jneuendorf** [comment]
I agree and that's how I fixed the behavior in my code.
But this `wontfix` basically means never to rely on [Funtion.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) at all.
Should this be mentioned in React Native's documentation? It takes way less time to read a small paragraph about this in the docs than debugging this. ^^

**Comment by SuhairZain** [comment]
@cpojer Is there any way to opt-out of class name mangling, maybe through the rn-cli.config.js file?
